apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: todo-app-secrets
  namespace: todo
spec:
  provider: aws
  parameters:
    region: us-east-1
    objects: |
      - objectName: "todo-dev-app-credentials"
        objectType: "secretsmanager"
        jmesPath:
          - path: DB_HOST
            objectAlias: DB_HOST
          - path: DB_PORT
            objectAlias: DB_PORT
          - path: DB_USER
            objectAlias: DB_USER
          - path: DB_PASSWORD
            objectAlias: DB_PASSWORD
          - path: DB_NAME
            objectAlias: DB_NAME
          - path: REDIS_HOST
            objectAlias: REDIS_HOST
          - path: REDIS_PORT
            objectAlias: REDIS_PORT
    # Replace <SECRET_NAME>: terraform -chdir=infra/terraform output -raw secrets_manager_secret_name
  secretObjects:
    - secretName: todo-secret
      type: Opaque
      data:
        - { objectName: DB_HOST,     key: DB_HOST }
        - { objectName: DB_PORT,     key: DB_PORT }
        - { objectName: DB_USER,     key: DB_USER }
        - { objectName: DB_PASSWORD, key: DB_PASSWORD }
        - { objectName: DB_NAME,     key: DB_NAME }
        - { objectName: REDIS_HOST,  key: REDIS_HOST }
        - { objectName: REDIS_PORT,  key: REDIS_PORT }