apiVersion: elbv2.k8s.aws/v1beta1
kind: TargetGroupBinding
metadata:
  name: todo-frontend-tgb
  namespace: todo
spec:
  serviceRef:
    name: todo-frontend-svc
    port: 80
  targetGroupARN: __FRONTEND_TG_ARN__
  targetType: ip

---

apiVersion: elbv2.k8s.aws/v1beta1
kind: TargetGroupBinding
metadata:
  name: todo-backend-tgb
  namespace: todo
spec:
  serviceRef:
    name: todo-backend-svc
    port: 80
  targetGroupARN: __BACKEND_TG_ARN__
  targetType: ip
