apiVersion: elbv2.k8s.aws/v1beta1
kind: TargetGroupBinding
metadata:
  name: todo-frontend-tgb
  namespace: todo
spec:
  serviceRef:
    name: todo-frontend-svc
    port: 80
  targetGroupARN: arn:aws:elasticloadbalancing:us-east-1:668076964228:targetgroup/todo-dev-frontend-tg/a8b3a3ac23c3df64
  targetType: ip

---

apiVersion: elbv2.k8s.aws/v1beta1
kind: TargetGroupBinding
metadata:
  name: todo-backend-tgb
  namespace: todo
spec:
  serviceRef:
    name: todo-backend-svc
    port: 80
  targetGroupARN: arn:aws:elasticloadbalancing:us-east-1:668076964228:targetgroup/todo-dev-backend-tg/9e309603c0e38fae
  targetType: ip
