apiVersion: v1
kind: Secret
metadata:
  name: prometheus-additional-scrape-configs
  namespace: monitoring
stringData:
  additional-scrape-configs.yaml: |
    - job_name: 'todo-backend'
      kubernetes_sd_configs:
      - role: endpoints
        namespaces:
          names:
          - todo
      relabel_configs:
      - source_labels: [__meta_kubernetes_service_name]
        action: keep
        regex: todo-backend-svc
      - source_labels: [__meta_kubernetes_endpoint_port_name]
        action: keep
        regex: http
      - source_labels: [__meta_kubernetes_endpoint_address_target_kind, __meta_kubernetes_endpoint_address_target_name]
        separator: ;
        regex: Pod;(.*)
        target_label: pod
        replacement: ${1}
        action: replace
      - source_labels: [__meta_kubernetes_namespace]
        target_label: namespace
        action: replace
      - source_labels: [__meta_kubernetes_service_name]
        target_label: service
        action: replace
      - source_labels: [__meta_kubernetes_pod_name]
        target_label: pod
        action: replace
      - source_labels: [__meta_kubernetes_pod_container_name]
        target_label: container
        action: replace
      - target_label: endpoint
        replacement: http
